apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-kotlin
  labels:
    app: catalog-service-kotlin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-kotlin
  template:
    metadata:
      labels:
        app: catalog-service-kotlin
    spec:
      containers:
        - name: catalog-service-kotlin
          image: catalog-service-kotlin
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://polar-postgres/polardb_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://catalog-config-service:8888
